const mongoose=require("mongoose")
 const applicationShcema=new mongoose.Schema({
    company:String,
    category:String,
    coverLetter:String,
    createAt:{
        type:Date,
        default:Date.now,
    },
    Application:Object,
    user:Object,
    status:{
        type:String,
        enum:["pending","accepted","rejected","interview"],
        default:"pending"
    },
    time:{
        type:String,
    default:null},
    room:{
        type:String,
    default:null
    },
    link:{
        type:String,
    default:null
    },
    date:{
        type:String,
    default:null
    }
 })
 module.exports=mongoose.model("Application",applicationShcema)